# .circleci/config.yml
version: 2
jobs:
  npm_install:
    docker:
      - image: circleci/node:16.13.1
    steps:
      - checkout
      - run: npm i
  eslint:
    docker:
      - image: circleci/node:16.13.1
    steps:
      - checkout
      - run:
          name: Run Eslint
          command: node_modules/.bin/eslint resources --ext js,jsx        
  jest:
    resource_class: large
    docker:
      - image: circleci/node:16.13.1
    steps:
      - checkout
      - restore_cache:
          name: Restore node_modules from cache
          key: node_modules-v1-{{ checksum "yarn.lock" }}
      - restore_cache:
          name: Restore precompiled translations from cache
          key: precompiled-translations-v1-{{ .Branch }}-{{ .Revision }}

      - run:
          name: Run Jest (if needed)
          command: node_modules/.bin/jest resources --silent --maxWorkers 4

workflows:
  version: 2
  run_tests:
    jobs:
      - yarn_install
      - eslint:
          requires:
            - yarn_install
      - jest:
          requires:
            - yarn_install

  # build:
    # docker:
      # - image: circleci/node:10
    # steps:
      # - checkout
      # - eslint:
        # - run: ./node_modules/.bin/eslint --fix front-end
      # Download and cache dependencies.
      # - restore_cache:
          # keys:
          # - v1-dependencies-{{ checksum "package.json" }}
          # Fallback to using the latest cache if no exact match is found.
          # - v1-dependencies-
      # - run: npm install
      # - save_cache:
          # paths:
            # - node_modules
          # key: v1-dependencies-{{ checksum "package.json" }}
      # Build the application.
      # - run: npm run generate
      # Run the FTP deployment script.
      # - run: npm run ftp-deploy