name: Publish Website to CPanel
on: 
  push:
    branches:
      - master
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        port: 21
        protocol: ftp
        server-dir: /
  run-commands:
    needs: web-deploy
    name: Run SSH command 
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: whoami
        host: 'beta.grupo.host'
        username: 'betagrupo'
        password: 'eLvjns6lN'
        port: '22'
    # name: Run SSH command appleboy
    # runs-on: ubuntu-latest
    # steps:
    # - name: executing remote ssh commands using ssh
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: 'beta.grupo.host'
    #     username: 'betagrupo'
    #     password: 'eLvjns6lN'
    #     port: 22
    #     script: whoami
        # script: composer install --no-dev

    # - name: 🚚 Get latest code
    #   uses: actions/checkout@v2
    # - name: Running SSH command  
    #   # You may pin to the exact commit or the version.
    #   # uses: garygrossgarten/github-action-ssh@d2ce399984eed21f8cf2a26d28ba309e1ed52fc5
    #   uses: garygrossgarten/github-action-ssh@v0.6.3
    #   with:
    #     # Command to execute on the remote server.
    #     command: composer install --no-dev
    #     # Hostname or IP address of the server.
    #     host: ${{ secrets.FTP_SERVER }}
    #     # Username for authentication.
    #     username: ${{ secrets.FTP_USER }}
    #     # Port number of the server.
    #     port: 22
    #     # File Location or string that contains a private key for either key-based or hostbased user authentication (OpenSSH format)
    #     privateKey: ${{ secrets.CPANEL_PRIVATE_KEY }}
    #     # Password for password-based user authentication.
    #     password: ${{ secrets.FTP_PASS }}
    #     # For an encrypted private key, this is the passphrase used to decrypt it.
    #     # passphrase: # optional
    #     # # Try keyboard-interactive user authentication if primary user authentication method fails.
    #     # tryKeyboard: # optional
