name: Deploy via ftp
on: 
  push:
    branches:
      - main
jobs:
  deploy:
    name: ftpToCPanel
    runs-on: ubuntu-latest
    steps:
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        # localDir: "dist"
        remoteDir: "public_html"
        # options: "--delete --asci"
